version: '3.9'

services:
  backend:
    image: '${DOCKER_IMAGE_BACKEND}:${TAG-latest}'
    env_file:
      - .env
    volumes:
      - .:/app  # Монтируем текущую директорию в /app внутри контейнера

