version: '3.9'
services:
  backend:
    ports:
      - '8001:8001'  # Host

    volumes:
      - .:/app  # Mount current dir into app
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TERM=`xterm-256color`

    build:
      context: ./
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}

    tty: true
    command: /app/root/start-reload.sh
