version: '3.9'

services:
  backend:
    image: '${DOCKER_IMAGE_BACKEND}:${TAG-latest}'
#    env_file:
#      - .env
    secrets:
      - env_file

    volumes:
      - .:/app  # Монтируем текущую директорию в /app внутри контейнера
      - ./result:/app

secrets:
  env_file:
    file: .env
