version: '3.9'
services:
  backend:
    ports:
      - 127.0.0.1:8001:8001  # Host

    volumes:
      - .:/app  # Mount current dir into app
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TERM=`xterm-256color`

    network_mode: "host"

    build:
      context: ./
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}

    tty: true
    command: /app/root/start-reload.sh
