[project]
name = "2024-09-08-svaha-mini-back"
version = "0.1.0"
description = "Add your description here"
dependencies = [
    "fastapi>=0.114.0",
    "uvicorn>=0.30.6",
    "pydantic-settings>=2.4.0",
    "aio-pika>=9.4.3",
    "aioredis>=2.0.1",
    "redis>=5.0.8",
    "ulid-py>=1.1.0",
    "boto3>=1.35.18",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/_2024_09_08_svaha_mini_back"]
